//! `new-pack` subcommand: generates a complete method pack crate scaffold.

use std::fs;
use std::path::{Path, PathBuf};

/// Generate a new method pack crate under `parent_dir/spinoza-pack-<pack_name>`.
///
/// Creates:
/// - `Cargo.toml`
/// - `src/lib.rs` (with MethodPack impl, register_pack!, stub builder)
/// - `tests/conformance.rs` (with conformance harness test)
/// - `README.md`
pub fn generate_new_pack(pack_name: &str, parent_dir: &Path) -> Result<PathBuf, String> {
    // Validate pack name: only lowercase alphanumeric and underscores.
    if pack_name.is_empty() {
        return Err("pack name must not be empty".to_string());
    }
    if !pack_name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
    {
        return Err(format!(
            "pack name '{pack_name}' must contain only lowercase letters, digits, and underscores"
        ));
    }

    let crate_name = format!("spinoza-pack-{pack_name}");
    let crate_dir = parent_dir.join(&crate_name);

    if crate_dir.exists() {
        return Err(format!("directory already exists: {}", crate_dir.display()));
    }

    // Create directories.
    let src_dir = crate_dir.join("src");
    let tests_dir = crate_dir.join("tests");
    fs::create_dir_all(&src_dir)
        .map_err(|e| format!("failed to create {}: {e}", src_dir.display()))?;
    fs::create_dir_all(&tests_dir)
        .map_err(|e| format!("failed to create {}: {e}", tests_dir.display()))?;

    // Compute identifiers.
    let pack_struct = to_pascal_case(pack_name) + "Pack";
    let builder_struct = to_pascal_case(pack_name) + "Builder";

    // Write Cargo.toml.
    let cargo_toml = format!(
        r#"[package]
name = "{crate_name}"
version.workspace = true
edition.workspace = true

[dependencies]
spinoza-core = {{ path = "../spinoza-core" }}

[dev-dependencies]
spinoza-core = {{ path = "../spinoza-core" }}
"#,
    );
    fs::write(crate_dir.join("Cargo.toml"), cargo_toml)
        .map_err(|e| format!("failed to write Cargo.toml: {e}"))?;

    // Write src/lib.rs.
    let lib_rs = format!(
        r#"//! spinoza-pack-{pack_name}: Method pack scaffold.
//!
//! Generated by `spinoza-devtools new-pack {pack_name}`.
//! Fill in your operator, preconditioner, and builder implementations.

use spinoza_core::{{
    BuiltProblem, Capability, CaseSpec, MethodPack, MethodRegistry, ProblemBuilder,
}};

// ---------------------------------------------------------------------------
// Pack definition
// ---------------------------------------------------------------------------

#[derive(Default)]
pub struct {pack_struct};

static CAPABILITIES: &[Capability] = &[
    // TODO: add the capabilities your pack provides, e.g.:
    // Capability::SpaceH1Scalar,
    // Capability::OperatorLaplacian,
    Capability::SolverCG,
];

impl MethodPack for {pack_struct} {{
    fn name(&self) -> &'static str {{
        "{pack_name}"
    }}
    fn version(&self) -> &'static str {{
        env!("CARGO_PKG_VERSION")
    }}
    fn capabilities(&self) -> &'static [Capability] {{
        CAPABILITIES
    }}
    fn register(&self, registry: &mut MethodRegistry) {{
        registry.register_builder(Box::new({builder_struct}));
    }}
}}

spinoza_core::spinoza_register_pack!({pack_struct});

// ---------------------------------------------------------------------------
// Problem builder stub
// ---------------------------------------------------------------------------

struct {builder_struct};

impl ProblemBuilder for {builder_struct} {{
    fn name(&self) -> &str {{
        "{builder_struct}"
    }}

    fn equation_type(&self) -> &str {{
        // TODO: replace with your equation type
        "{pack_name}"
    }}

    fn supported_dimensions(&self) -> &[u8] {{
        &[2]
    }}

    fn supported_backends(&self) -> &[&str] {{
        &["assembled"]
    }}

    fn build(
        &self,
        _spec: &CaseSpec,
        _backend: &str,
        _precond_hint: &str,
        _nx: usize,
        _ny: usize,
        _nz: usize,
        _registry: &MethodRegistry,
    ) -> Result<BuiltProblem, String> {{
        // TODO: implement your operator assembly and problem construction
        Err("not yet implemented".to_string())
    }}
}}
"#,
    );
    fs::write(src_dir.join("lib.rs"), lib_rs)
        .map_err(|e| format!("failed to write src/lib.rs: {e}"))?;

    // Write tests/conformance.rs.
    let conformance_test = format!(
        r#"//! Conformance test for the {pack_name} method pack.

#[test]
fn pack_conforms() {{
    // Anchor the pack so inventory discovers it.
    let _ = spinoza_pack_{pack_name}::{pack_struct};
    spinoza_core::conformance::assert_pack_conforms("{pack_name}");
}}
"#,
    );
    fs::write(tests_dir.join("conformance.rs"), conformance_test)
        .map_err(|e| format!("failed to write tests/conformance.rs: {e}"))?;

    // Write README.md.
    let readme = format!(
        r#"# spinoza-pack-{pack_name}

Method pack for the Spinoza multiphysics framework.

Generated by `spinoza-devtools new-pack {pack_name}`.

## Getting started

1. Edit `src/lib.rs` to implement your operator and builder.
2. Update `CAPABILITIES` with the capabilities your pack provides.
3. Add the crate to the workspace `Cargo.toml`:
   ```toml
   members = [
       # ...
       "crates/spinoza-pack-{pack_name}",
   ]
   ```
4. Add the crate as a dependency in `spinoza-devtools/Cargo.toml`:
   ```toml
   spinoza-pack-{pack_name} = {{ path = "../spinoza-pack-{pack_name}" }}
   ```
5. Anchor the pack in `spinoza-devtools/src/main.rs` and `solve_case.rs`:
   ```rust
   let _ = spinoza_pack_{pack_name}::{pack_struct};
   ```
6. Run conformance tests: `cargo test -p spinoza-pack-{pack_name}`
"#,
    );
    fs::write(crate_dir.join("README.md"), readme)
        .map_err(|e| format!("failed to write README.md: {e}"))?;

    Ok(crate_dir)
}

/// Convert a snake_case name to PascalCase.
fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    upper + chars.as_str()
                }
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_conversion() {
        assert_eq!(to_pascal_case("my_diffusion"), "MyDiffusion");
        assert_eq!(to_pascal_case("poisson"), "Poisson");
        assert_eq!(to_pascal_case("block2x2"), "Block2x2");
    }

    #[test]
    fn pack_name_validation_rejects_uppercase() {
        let dir = std::env::temp_dir().join("spinoza_test_newpack_reject");
        let result = generate_new_pack("MyPack", &dir);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("lowercase"));
    }

    #[test]
    fn pack_name_validation_rejects_empty() {
        let dir = std::env::temp_dir().join("spinoza_test_newpack_empty");
        let result = generate_new_pack("", &dir);
        assert!(result.is_err());
    }
}
